CREATE TABLE BreedGroups (
	Id		UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name	NVARCHAR(50) NOT NULL
);

CREATE TABLE DogBreeds (
	Id						UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name					NVARCHAR(50) NOT NULL,
	GroupId					UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES BreedGroups(Id),
	MinimumWeight			INT NOT NULL DEFAULT 0,
	MaximumWeight			INT NOT NULL DEFAULT 0,
	MinimumHeight			INT NOT NULL DEFAULT 0,
	MaximumHeight			INT NOT NULL DEFAULT 0,
	MinimumLifeExpectancy	INT NOT NULL DEFAULT 0,
	MaximumLifeExpectancy	INT NOT NULL DEFAULT 0,
	Description				NVARCHAR(100) NULL,
	BreedPopularity			INT NOT NULL DEFAULT 0
);

CREATE TABLE DogOwners (
	Id			UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	FirstName	NVARCHAR(50) NOT NULL,
	LastName	NVARCHAR(50) NOT NULL,
	Email		NVARCHAR(50) NOT NULL,
	Phone		NVARCHAR(10) NOT NULL,
	Age			INT NOT NULL DEFAULT 0,
	CountryCode	NVARCHAR(3) NOT NULL DEFAULT 'USA'
);

CREATE TABLE Dogs (
	Id			UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name		NVARCHAR(50) NOT NULL,
	Age			INT NOT NULL DEFAULT 0,
	BreedId		UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES DogBreeds(Id),
	OwnerId		UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES DogOwners(Id)
);


